// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzoaecypsakpyzmnyuky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56b2FlY3lwc2FrcHl6bW55dWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODc3MjMsImV4cCI6MjA1ODk2MzcyM30.HeEasNByp0scRp1Aygn4SkW203dbfgeDo0q5HqH7lsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);